---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-stack-shared
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: {{ .Values.llamaStackShared.repoURL }}
    targetRevision: {{ .Values.llamaStackShared.targetRevision }}
    path: {{ .Values.llamaStackShared.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.llamaStackShared.namespace }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
