# Default values for llama-stack-instance
# This is a YAML-formatted file.

# Username for this instance (will be overridden by ApplicationSet)
username: user1

# Cluster configuration, for templating routes
deployer:
  domain: apps.cluster.example.com
# Model configuration
models:
  inference:
    name: qwen3-4b-instruct
    displayName: Qwen 3 4B Instruct 2507
  safety:
    name: llama-guard-3-1b
    displayName: Llama Guard 3 1B
